INCLUDE_PATHS += /usr/include/SDL2

INCLUDE_PATHS += $(SRC_DIR)
INCLUDE_PATHS += $(SRC_DIR)/i2c
INCLUDE_PATHS += $(SRC_DIR)/tools
# INCLUDE_PATHS += $(SRC_DIR)/X11_lib
INCLUDE_PATHS += $(SRC_DIR)/PCA9685
INCLUDE_PATHS += $(SRC_DIR)/pwm_servo
INCLUDE_PATHS += $(SRC_DIR)/hexapod_leg
INCLUDE_PATHS += $(SRC_DIR)/robot_spec
# INCLUDE_PATHS += $(SRC_DIR)/joy
