############################################################
# System control configuration parameters
############################################################

# Start in daemon (background) mode and release terminal.
# daemon off
# daemon on

# Start in Setup-Mode, daemon disabled.
setup_mode off

# File to store the process ID.
# pid_file /var/run/motion/motion.pid

# File to write logs messages into. If not defined, stderr and syslog is used.
log_file /var/log/motion/motion.log

# Level of log messages [1..9] (EMG, ALR, CRT, ERR, WRN, NTC, INF, DBG, ALL).
log_level 6

# Target directory for pictures, snapshots, and movies (not needed for streaming)
target_dir /var/lib/motion

############################################################
# Webcontrol configuration parameters
############################################################

# Port number used for the webcontrol.
webcontrol_port 0

# Restrict webcontrol connections to the localhost.
webcontrol_localhost on

############################################################
# Camera config files - One for each camera.
############################################################

# Include the individual camera configuration files
camera /opt/hexafpv/def_cam.conf
# camera /etc/motion/camera2-dist.conf

