video_device /dev/video0
width 640
height 480
framerate 30
stream_maxrate 30

rotate 180
threshold 0
minimum_motion_frames 1
emulate_motion on
picture_output off
movie_output off
stream_port 8081
stream_localhost off
